# shellcheck shell=bash
# bashrc.d/004.completion.bash
# ------------------------------------------------------------------------------
# Bash Completion System Configuration
# ------------------------------------------------------------------------------

# Source the global bash-completion script if it exists.
# This provides the core completion functions.
if [[ -f /usr/share/bash-completion/bash_completion ]]; then
  # shellcheck disable=SC1091
  . /usr/share/bash-completion/bash_completion
elif [[ -f /etc/bash_completion ]]; then
  # shellcheck disable=SC1091
  . /etc/bash_completion
fi

# Source Homebrew's bash-completion if it exists.
if [[ -f "$(brew --prefix)/etc/bash_completion" ]]; then
    # shellcheck disable=SC1090,SC1091
    . "$(brew --prefix)/etc/bash_completion"
fi

# Create a directory for our own custom completion scripts.
# This is where we will place scripts generated by tools like 'just'.
mkdir -p ~/.bash_completion.d

# Finally, source all scripts within our custom completions directory.
# This makes our custom completions active.
if [ -d ~/.bash_completion.d ]; then
  for comp_file in ~/.bash_completion.d/*; do
    # The '.' command is an alias for 'source'
    # shellcheck disable=SC1090
    . "$comp_file"
  done
fi
