# shellcheck shell=bash
# bashrc.d/004.completion.bash
# ------------------------------------------------------------------------------
# Bash Completion System Configuration
# ------------------------------------------------------------------------------

# Source the global bash-completion script if it exists.
# This provides the core completion functions.
if [[ -f /usr/share/bash-completion/bash_completion ]]; then
  # shellcheck disable=SC1091
  . /usr/share/bash-completion/bash_completion
elif [[ -f /etc/bash_completion ]]; then
  # shellcheck disable=SC1091
  . /etc/bash_completion
fi

# Source Homebrew's bash-completion if it exists.
if command -v brew &>/dev/null; then
    _brew_prefix="$(brew --prefix)"
    if [[ -f "${_brew_prefix}/etc/bash_completion" ]]; then
        # shellcheck disable=SC1090,SC1091
        . "${_brew_prefix}/etc/bash_completion"
    fi
    unset -v _brew_prefix
fi

# Create a directory for our own custom completion scripts.
# This is where we will place scripts generated by tools like 'just'.
mkdir -p "${HOME}/.bash_completion.d"

# Finally, source all scripts within our custom completions directory.
# This makes our custom completions active.
if [[ -d "${HOME}/.bash_completion.d" ]]; then
    for comp_file in "${HOME}"/.bash_completion.d/*; do
        # shellcheck disable=SC1090
        [[ -f "$comp_file" ]] && . "$comp_file"
    done
fi
