#!/usr/bin/env bash

set -eu

session_file=""
role=""
message=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --file)
            session_file="$2"
            shift 2
            ;;
        --role)
            role="$2"
            shift 2
            ;;
        --message)
            message="$2"
            shift 2
            ;;
        *)
            exit 2
            ;;
    esac
done

[[ -f "$session_file" ]] || exit 0
jq -cn --arg role "$role" --arg message "$message" \
    '{role: $role, message: $message}' >> "$session_file"
