# $HOME/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# set PATH so it includes user's private bin if it exists
if [[ -d "${HOME}"/bin ]] ; then
    PATH="${PATH}":"${HOME}"/bin
fi

# Set up the XDG Base Directory Specification
XDG_FILE="${HOME}"/.bashrc.d/xdg_base_directory.bash
if [[ -f ${XDG_FILE} ]]; then
    source ${XDG_FILE}
fi

# If not running interactively, stop now
[[ -z "$PS1" || $- != *i* ]] && return
# When using rsync over ssh to older versions of bash, [[ -z $PS1 ]] returns
# true incorrectly, so we use [[ $- != *i* ]] as a backup

####################### BELOW ONLY RUNS ON PHYSICAL ###########################

# check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize &>/dev/null

# autocorrect spelling in cd calls
shopt -s cdspell &>/dev/null

# autocorrect spelling during completion
shopt -s dirspell &>/dev/null

# include dotfiles in pattern matching
shopt -s dotglob &>/dev/null

# enable double-starring paths
shopt -s globstar &>/dev/null

# enable advanced pattern matching
shopt -s extglob &>/dev/null

# turn off mail checking
unset -v MAILCHECK

# turn off annoying shell beep
hash setterm &>/dev/null && setterm -bfreq 0 -blength 0

# turn off flow control keys
hash stty &>/dev/null && stty -ixon

# do not let others write to my terminal
mesg n

# make less more friendly for non-text input files, see lesspipe(1)
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

# Gnome-terminal sets the wrong term string. Worse the right one doesn't report
# all the features in most distributions, so we set it to xterm-256color and
# hope for the best. This at least makes screen happy.
#
# Update: Apparently gnome terminal stops setting $COLORTERM in 3.13 and
# later. At that point it might be best to set up a start up command in gnome
# term: env TERM=xterm-256color /bin/bash
if [[ "$COLORTERM" == "gnome-terminal" ]]; then
    if [[ "$TERM" == "xterm" ]]; then
        export TERM=xterm-256color
    fi
fi

# enable programmable completion features
if [[ -f /etc/bash_completion ]] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Umask to set file permissions on creation
umask 077

# Set editor, but only if we find vim
hash vim &>/dev/null && export EDITOR=vim && export VISUAL=vim

# Set manpage reader to vim
#hash col && hash vim && export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""

# Load configuration subfiles
subfile_dir="${HOME}"/.bashrc.d/
if [[ -d ${subfile_dir} ]]; then
    for config in ${subfile_dir}/*.bash; do
        source "${config}"
    done
fi
# Unset variables to avoid polluting our shell's namespace
unset -v config
unset -v subfile_dir
