# $HOME/.bash_logout: executed by bash(1) when login shell exits.

# $SHLVL keeps track of how many times we've run the a shell. If we run
# multiple shells nested within eachother, this only clears when the final one
# is closed.
if [[ "$SHLVL" = 1 ]]; then
    # when leaving the console clear the screen to increase privacy
    [[ -x /usr/bin/clear_console ]] && /usr/bin/clear_console -q
fi
